import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import Footer from "./components/Footer/Footer";
import WhatsAppButton from "./components/WhatsAppButton/WhatsAppButton";
import "./globals.css";

import { urls } from "./Configs/urls";

const AlexandriaFont = Alexandria({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${AlexandriaFont.variable}  antialiased`}
      >
        {children}
        <Footer/>
        <WhatsAppButton whatsapp_url={urls.whatsapp}/>
      </body>
    </html>
  );
}
